# netlify.toml
[build]
  command = "npm run build"
  publish = "out"
  functions = "/antitesis/netlify/functions"

# Configuración para SPA (aplicación de una sola página)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200